[project]
name = "attempt3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-socketio>=5.5.1",
    "watchdog>=6.0.0",
]
